{% set name = "trafaret" %}
{% set version = "2.0.1" %}
{% set sha256 = "15f8978777f1ea98158019d8bd7bb141921cafb12991ae6611e8bc28b32208ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - trafaret
    - trafaret.extras
    - trafaret.utils
    - trafaret.visitor
    - trafaret.constructor

about:
  home: https://github.com/Deepwalker/trafaret
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Ultimate transformation library that supports validation, contexts and aiohttp'

  description: |
    Trafaret is rigid and powerful lib to work with foreign data, configs etc.
    It provides simple way to check anything, and convert it accordingly to
    your needs.
  doc_url: http://trafaret.readthedocs.io/en/latest/
  dev_url: https://github.com/Deepwalker/trafaret

extra:
  recipe-maintainers:
    - elatt
    - dsakagi
    - peterhurford
    - madmott
    - nott
    - Deepwalker
